# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo {c:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/new/Ball.v}
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/new/Balls_Moving.v}
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/new/Border.v}
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/imports/Counter_16Bit.v}
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/imports/Edge_Detector.v}
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/new/Pixels.v}
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/imports/Ring_Counter.v}
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/imports/Selector.v}
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/new/Top_Level.v}
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/imports/countUD4L.v}
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/imports/hex7seg.v}
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/imports/Downloads/labVGA_clks.v}
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/new/GameState.v}
  {C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/sources_1/imports/LFSR.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/constrs_1/imports/CSE 100/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Cole/Desktop/UCSC/CSE 100/Labs/Lab 6/Lab6/Lab6.srcs/constrs_1/imports/CSE 100/Basys3_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top_Level -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Level_utilization_synth.rpt -pb Top_Level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
